title: 2025 Step Challenge 
description: 10k steps a day for 2025
baseurl: "/step-tracker"
url: "" # Your GitHub Pages URL will go here

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

include:
  - assets